Fix error of packaging conflict
error: build/soong/fsgen/Android.bp:31:1:
module+"lineage_zenfone7_generated_vendor_image" variant
"android_common"+(created by module "soong_filesystem_creator" variant
"android_common"): packaging conflict at　...

Signed-off-by: BrightTwikling <DF.SJbbba5@gmail.com>